### ISSUE TITLE
比較用のPHP7.x,5.6も欲しい

### ISSUE THREAD

**Issue by ramsydx** [KEINOS/Dockerfile_of_PHP8-JIT#10]
同一条件での比較用に、PHP7.4/7.3/7.2/7.1/7.0/5.6 も入れられんでしょうか。

**Comment by KEINOS** [comment]
@ramsydx 

確かに JIT を有効にしたからといって、すべてが速くなるというわけではないので、速度比較は大事だと思います。

「同一条件で入れられないか」というのは、README.md の下部にある JIT の「あり・なし」のベンチ結果の箇所に、同じテスト・スクリプトで PHP 7.4〜5.6 のベンチ結果を記載して欲しい、ということでよろしいでしょうか。

それとも、比較用に JIT を有効にした PHP7.4 〜 5.6 も欲しいということでしょうか。

後者であった場合は、残念ながらそもそもの設計の違いからできません。前者なら Medium に、このイメージを使っていただいたベンチ結果の記事がありました。ご参考までに。

- [How fast is PHP-8 going to be?](https://levelup.gitconnected.com/how-fast-is-php-8-going-to-be-f7fdc111cd6) by Pedro Escudero @ Medium

**Comment by KEINOS** [comment]
@ramsydx 

PHP 5.6〜8.0 のベンチマーク結果を README.md に載せてみました！こっちの方がいいですね。

- [README.md#perfomance-comparison](https://github.com/KEINOS/Dockerfile_of_PHP8-JIT/tree/642f0de66edf56da4d05f06e7af3ef3dc298859c#perfomance-comparison)
