### ISSUE TITLE
Pecl is gone

### ISSUE THREAD

**Issue by jaapio** [KEINOS/Dockerfile_of_PHP8-JIT#13]
In the latest image pecl isn't available anymore, where it was before. Is it possible to readd pecl?

**Comment by KEINOS** [comment]
I believe it's never been in the image. The official image `php:7-alpine` does though.

But, indeed, it's worth adding `pecl` command or a script to add PECL packages such like `docker-php-ext-pecl` to lighten the image size.

I'll look into it.

**Comment by jaapio** [comment]
I did have an image based on yours containing pecl. So somehow it was there.
Thanks for looking in to this :+1:

**Comment by KEINOS** [comment]
@jaapio 

**I featured the `pecl` command** as requested. Also, featured the `docker-php-ext-pecl` script that installs PECL packages from the source.

- See [README.md](https://github.com/KEINOS/Dockerfile_of_PHP8-JIT#advanced-usage)

And thanks for the requesting which I realized that `docker-php-ext-install` didn't run on-the-fly, so I did fix them as well.

Please update the image and try.

```bash
docker pull keinos/php8-jit:latest
```

Here are some samples that did work on macOS Mojave (Intel) and RaspberryPi3 (ARM7).
- https://github.com/KEINOS/Dockerfile_of_PHP8-JIT/tree/php8-jit/samples
